### ISSUE TITLE
Information about the Marlin Braille compilation

### ISSUE THREAD

**Issue by juliano-lopes** [BrailleRapSP/BrailleRapSP#3]
Hello,

to try to build Marlin Braille application, an error is displayed:

In file included from sketch\Marlin_main.cpp:314:0:
sketch\endstop_interrupts.h: In function 'void setup_endstop_interrupts()':
endstop_interrupts.h:148:7: error: non-constant condition for static assertion
       static_assert(digitalPinToPCICR(Y_MIN_PIN) != NULL, "Y_MIN_PIN is not interrupt-capable");
       ^~~~~~~~~~~~~
In file included from sketch\Marlin_main.cpp:314:0:
endstop_interrupts.h:54:57: error: reinterpret_cast from integer to pointer
                                     WITHIN(p, 62, 69) ? &PCICR : (uint8_t*)0 )
                                                         ^
sketch\endstop_interrupts.h:148:21: note: in expansion of macro 'digitalPinToPCICR'
       static_assert(digitalPinToPCICR(Y_MIN_PIN) != NULL, "Y_MIN_PIN is not interrupt-capable");
                     ^~~~~~~~~~~~~~~~~
exit status 1
non-constant condition for static assertion

It's been used the arduino mega.
I'd like to know if you can helpe me, please. I couldn't find how I can build the application on the documentation.

Best regards.

**Comment by crocsg** [comment]
Hello Julianos
i just check the compilation on Arduino IDE 1.8.12, and i have the same error. I gave a few try with Arduino IDE 1.8.9 and i don't have the issue. This is maybe a quick workaround if you can get Arduino IDE 1.8.9.  I will have a deeper look in the next few days and deliver a new release.

Best Regards

**Comment by crocsg** [comment]
Hello Julianos
i just delivered a patch in the master branch that work well with Arduino 1.8.12
